version = 1

[[analyzers]]
name = "docker"

[[analyzers]]
name = "javascript"

[[analyzers]]
name = "go"

  [analyzers.meta]
  import_root = "github.com/james-deepsource/grafana"

[[analyzers]]
name = "secrets"